### PR TITLE
Add support for special characters

### PR DESCRIPTION
**Pull request by gregorni**
Practical for sending links, text with punctuation, Spanish text, email adresses, and so on.

### CODE REVIEW

**Comment by gregorni** [comment]
If the character is outside the list of available characters, a hashtag gets inserted, the way most online morse decoders do it.

**Comment by fkinoshita** [comment]
Hi, thank you for the contribution!

Is it the best practice to use this try catch block in cases like this with python? I'm just curious since I'm not really a python guy 😅️

**Comment by gregorni** [comment]
Well, I wanted to avoid creating a super long, complex regex, so I stuck with the `try: except:`, and since an exception gets thrown whenever the character isn't in the list, the code *does work*. As to what's best/common practice, I'm not sure.

**Comment by gregorni** [comment]
Oh, I'll have to fix that. I'll work on it this evening.

**Comment by gregorni** [comment]
Would adding a `' ': '/'` to the list be a good solution?

**Comment by fkinoshita** [comment]
Hi, it's working great! However there's a little issue when translating from Morse, the code doesn't understand the '#' in there now.

**Comment by gregorni** [comment]
Should it really? I mean, the `#` means that the sign isn't supported by Morse code and could be anything. I think just not translating it would be a good way to handle the case of someone entering it.

**Review by gregorni — COMMENTED** [review]
This wasn't needed, since nothing gets translated anyway if the character isn't in the list.

**Comment by fkinoshita** [comment]
What I mean is that when translating from Morse, it just doesn't show anything where the "#" character would be, which is confusing, showing the same "#" character would be enough.

**Comment by gregorni** [comment]
Ah, good point.

**Pull request merged**
