### PR TITLE
Remove modes and add more characters

### LINKED ISSUE #1: Move away from modes
It would be cool to not have explicit modes and instead just allow the user to write messages on both text views and put the output of that in the other, not focused text view.

Just tried that right now but python really didn't like that. :(

### PR DESCRIPTION
**Pull request by axtloss**
Allows users to simply type in the separate boxes to translate them instead of having to switch between modes, resolves #1 

also adds some special characters

### CODE REVIEW

**Comment by fkinoshita** [comment]
Hi, thank you for the contribution.

Your commit is doing a lot of things though, it's adding more characters, making it possible to input or both text views, etc...

Could you please split these up into different commits?

And btw there's already a pull request that adds more characters so that's not needed on this pull request as well.

**Comment by axtloss** [comment]
Seems like I missed the pr for extra characters, I will revert those changes, which would also fix the issue about having one commit do multiple things as the only change then would be being able to input in both text views

**Comment by axtloss** [comment]
I reverted the changes to add extra characters, this pr now only removes the modes

**Comment by fkinoshita** [comment]
Thanks!

**Pull request merged**
