### PR TITLE
Fix untranslated strings

### PR DESCRIPTION
**Pull request by sabriunal**
### Fix two strings seem untranslated
- Gettext already defined in application.py
- Fixes: https://github.com/fkinoshita/Telegraph/issues/40

### CODE REVIEW

**Comment by fkinoshita** [comment]
Thanks! By default Toasts have a timeout of 5 seconds, were they not dismissed?

**Comment by sabriunal** [comment]
> Thanks! By default Toasts have a timeout of 5 seconds, were they not dismissed?

I didn't wait that long. You are right. I can remove that part.

**Comment by fkinoshita** [comment]
Awesome, thank you very much!

**Comment by sabriunal** [comment]
Ekran Görüntüsü - 2023-10-15 14-23-41

**Comment by fkinoshita** [comment]
Oh, never looked at it in another language, it looks so cool!

**Pull request merged**
